import { Device } from './deviceTypes';

// Sample device data for development - will be replaced by API
export const sampleDevices: Device[] = [
  {
    id: 1,
    mac: "aa:bb:cc:dd:ee:01",
    hostname: "johns-macbook",
    vendor: "Apple",
    given_name: "John's MacBook Pro",
    ip: "192.168.1.100",
    user_agent: ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"],
    group: { id: 2, name: "Staff", is_default: false },
    is_active: true,
    has_custom_blocklist: false,
    first_seen: "2024-01-15T08:30:00Z",
    last_seen: "2024-01-20T15:45:00Z",
    is_mac_universal: false,
    os_name: "macOS",
    os_accuracy: 95,
    os_type: "general purpose",
    os_vendor: "Apple",
    os_family: "macOS",
    os_gen: "14",
    os_cpe: ["cpe:2.3:o:apple:macos:14:*:*:*:*:*:*:*"],
    os_last_updated: "2024-01-20T15:45:00Z",
    blocklist: {
      ads_trackers: false,
      gambling: true,
      social_media: false,
      porn: true,
      gaming: false,
      streaming: false,
      facebook: false,
      instagram: false,
      tiktok: true,
      netflix: false,
      youtube: false,
      ai: false,
      safesearch: true
    },
    ai_classification: {
      device_type: "laptop",
      device_category: "computer",
      confidence: 0.95,
      reasoning: "macOS device with typical laptop characteristics",
      indicators: ["macOS", "laptop", "work device"],
      last_classified: "2024-01-20T15:45:00Z"
    }
  },
  {
    id: 2,
    mac: "bb:cc:dd:ee:ff:02",
    hostname: "smart-tv-living",
    vendor: "Samsung",
    given_name: "Living Room TV",
    ip: "192.168.1.105",
    user_agent: [],
    group: { id: 4, name: "IoT", is_default: false },
    is_active: true,
    has_custom_blocklist: true,
    first_seen: "2024-01-10T12:00:00Z",
    last_seen: "2024-01-20T22:30:00Z",
    is_mac_universal: false,
    os_name: "Tizen",
    os_accuracy: 88,
    os_type: "embedded",
    os_vendor: "Samsung",
    os_family: "Linux",
    os_gen: "6.0",
    os_cpe: ["cpe:2.3:o:samsung:tizen:6.0:*:*:*:*:*:*:*"],
    os_last_updated: "2024-01-20T22:30:00Z",
    blocklist: {
      ads_trackers: true,
      gambling: true,
      social_media: false,
      porn: true,
      gaming: false,
      streaming: false,
      facebook: false,
      instagram: false,
      tiktok: false,
      netflix: false,
      youtube: false,
      ai: false,
      safesearch: true
    },
    ai_classification: {
      device_type: "smart_tv",
      device_category: "entertainment",
      confidence: 0.92,
      reasoning: "Samsung smart TV with streaming capabilities",
      indicators: ["smart_tv", "entertainment", "streaming"],
      last_classified: "2024-01-20T22:30:00Z"
    }
  },
  {
    id: 3,
    mac: "cc:dd:ee:ff:00:03",
    hostname: "iphone-guest",
    vendor: "Apple",
    given_name: "Guest iPhone",
    ip: "192.168.1.110",
    user_agent: ["Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)"],
    group: { id: 3, name: "Guests", is_default: false },
    is_active: false,
    has_custom_blocklist: false,
    first_seen: "2024-01-18T14:20:00Z",
    last_seen: "2024-01-19T16:45:00Z",
    is_mac_universal: true,
    os_name: "iOS",
    os_accuracy: 98,
    os_type: "mobile",
    os_vendor: "Apple",
    os_family: "iOS",
    os_gen: "17",
    os_cpe: ["cpe:2.3:o:apple:iphone_os:17.0:*:*:*:*:*:*:*"],
    os_last_updated: "2024-01-19T16:45:00Z",
    blocklist: {
      ads_trackers: false,
      gambling: true,
      social_media: true,
      porn: true,
      gaming: true,
      streaming: true,
      facebook: true,
      instagram: true,
      tiktok: true,
      netflix: true,
      youtube: true,
      ai: false,
      safesearch: true
    },
    ai_classification: {
      device_type: "smartphone",
      device_category: "mobile",
      confidence: 0.98,
      reasoning: "iPhone device with guest network access",
      indicators: ["smartphone", "mobile", "guest"],
      last_classified: "2024-01-19T16:45:00Z"
    }
  },
  {
    id: 4,
    mac: "dd:ee:ff:00:11:04",
    hostname: "wifi-printer",
    vendor: "HP",
    given_name: "Office Printer",
    ip: "192.168.1.120",
    user_agent: [],
    group: { id: 4, name: "IoT", is_default: false },
    is_active: true,
    has_custom_blocklist: false,
    first_seen: "2024-01-08T09:15:00Z",
    last_seen: "2024-01-20T11:20:00Z",
    is_mac_universal: false,
    os_name: "Linux",
    os_accuracy: 75,
    os_type: "embedded",
    os_vendor: "HP",
    os_family: "Linux",
    os_gen: "unknown",
    os_cpe: ["cpe:2.3:o:hp:linux:*:*:*:*:*:*:*:*"],
    os_last_updated: "2024-01-20T11:20:00Z",
    blocklist: {
      ads_trackers: true,
      gambling: true,
      social_media: true,
      porn: true,
      gaming: true,
      streaming: true,
      facebook: true,
      instagram: true,
      tiktok: true,
      netflix: true,
      youtube: true,
      ai: true,
      safesearch: true
    },
    ai_classification: {
      device_type: "printer",
      device_category: "office",
      confidence: 0.89,
      reasoning: "Network printer with Wi-Fi capabilities",
      indicators: ["printer", "office", "wifi"],
      last_classified: "2024-01-20T11:20:00Z"
    }
  },
  {
    id: 5,
    mac: "ee:ff:00:11:22:05",
    hostname: "gaming-pc",
    vendor: "Custom Build",
    given_name: "Gaming Rig",
    ip: "192.168.1.150",
    user_agent: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64)"],
    group: { id: 2, name: "Staff", is_default: false },
    is_active: true,
    has_custom_blocklist: true,
    first_seen: "2024-01-12T19:30:00Z",
    last_seen: "2024-01-20T23:15:00Z",
    is_mac_universal: false,
    os_name: "Windows 11",
    os_accuracy: 97,
    os_type: "general purpose",
    os_vendor: "Microsoft",
    os_family: "Windows",
    os_gen: "11",
    os_cpe: ["cpe:2.3:o:microsoft:windows:11:*:*:*:*:*:*:*"],
    os_last_updated: "2024-01-20T23:15:00Z",
    blocklist: {
      ads_trackers: false,
      gambling: false,
      social_media: false,
      porn: true,
      gaming: false,
      streaming: false,
      facebook: false,
      instagram: false,
      tiktok: false,
      netflix: false,
      youtube: false,
      ai: false,
      safesearch: true
    },
    ai_classification: {
      device_type: "desktop",
      device_category: "computer",
      confidence: 0.93,
      reasoning: "High-performance Windows desktop for gaming",
      indicators: ["desktop", "gaming", "high-performance"],
      last_classified: "2024-01-20T23:15:00Z"
    }
  }
];